// Flexible Visual System · 00-core — State, palette and colour rules — the shared state object every other file reads.
// One of the classic scripts fvs/index.html loads in order (fvs/js/00 … 99); they share one global scope.
// Architecture + file map: docs/FVS.md §Architecture.
'use strict';
/* ─────────────────────────────────────────────────────────────
   FVS — Flexible Visual System. First pass: Seeds → Components only
   (the Symbols/Pattern/Applications tiers from the reference brief are
   later phases, not built here).

   One canonical array of "items" (cx, cy, rotation, flipH, flipV, scale)
   per component feeds BOTH the canvas raster export and the SVG string —
   same discipline as vortex/js/render.js + svgexport.js: identical
   transform math in both places, so nothing can visually disagree
   between preview/PNG/SVG.
   ───────────────────────────────────────────────────────────── */

function ctrl(id) { return document.getElementById(id); }
function val(id) { return parseFloat(ctrl(id).value); }

const setStatus = Organica.status();

// Screen/Print output mode — shared/print-size-panel.js. Screen (default)
// is today's Scale-multiplier export, untouched; Print reveals a real
// physical size + DPI + bleed. Title says "(selection)" — FVS's "trim" is
// the selected component's own square frame, not a whole canvas, so the
// export is always scoped to whatever's picked in the gallery.
const printSizePanel = Organica.printSizePanel(document.getElementById('print-size-host'), {
  idPrefix: 'ps',
  title: 'Print (selection)',
  onChange: () => {
    document.getElementById('screen-scale-rows').style.display = printSizePanel.getMode() === 'print' ? 'none' : '';
  },
});

// Paper tile dropdown (Organica.selectPicker) — declared up here: renderSeedPreview, which
// refreshes its "Current Element" thumbnail, runs during boot before the tile code below.
const TILE_PICK_REG = {};
let tilePicker = null;
const state = {
  components: [],   // [{id, ruleSource, cells:[{rotation,flipH,flipV,scale,content} x4]}]
                     // cell.content: null (default, follow the shared Element) or
                     // {source:'seed', seedType, seedParams} — set live in Component Edit mode
  selectedId: null,
  selectionExplicit: false,   // true once selectedId was set by a real action (click/Generate/quick-save/Library load), not just the starter gallery's own passive default — gates the .selected border in renderGallery()
  // ── Component Edit mode — a big single-component view (enterComponentEditMode)
  // where each cell is clickable and, once selected, the Element sidebar edits
  // THAT cell's own shape live. Editing never mutates the source component —
  // "Save as new" (saveComponentEditAsNew) pushes a fresh gallery candidate.
  componentEditMode: false,
  componentEditId: null,          // the component being edited FROM (read-only source, never mutated)
  componentEditCells: null,       // working copy of cells, edited in place while in this mode
  componentEditGrid: null,        // grid snapshot at entry — fixed for the duration (per design decision)
  componentEditSelectedCell: null,   // index into componentEditCells, or null
  componentEditDefaultSeed: null,    // seedForSnapshot() frozen at entry — the shared Element every non-overridden cell keeps using
  componentEditDefaultAppearance: null,   // getElementAppearance() frozen at entry — same idea, for Style/Width/Length/Scale/Move
  componentAutoGenerated: null,       // null = never populated this session; true = the current gallery is the live, untouched starter set; false = the user did something explicit (Generate/Manual/Clear/a Library load)
  componentAutoGenSignature: null,    // signature of (seed, appearance, cell count) at the moment the starter set was last (re)built
  colors: ['#000000'],   // the centralised Palette (Ink) — see buildPalette()/colorAt() below
  paperColor: '#ffffff',   // the ground every render/export paints against
  customSeed: null,   // {d, normTx, normTy, normScale} from an uploaded SVG, or null
  layers: null,       // null = a plain single-shape Element. Else {items:[{id,name,role:'fill'|'mask'|'container',ink:'cell'|slot,place:{mx,my,scale,rotate},seed}], active} — a stack, bottom→top; the Seed panel edits items[active]
  componentRole: 'normal',           // 'normal' | 'container' | 'mask' — this Component's own silhouette used as a clip/knockout boundary for underlyingComponentName
  underlyingComponentName: null,     // another saved Component Library entry's name, or null
  loomGrid: null,   // {cellShape, cells, inner:{width,height}} from Organica.loadLoomGrid, or null until a file is imported
  activeTier: 'element',   // 'element' | 'component' | 'symbol' | 'figure'
  splitOriginal: null, splitApplied: null,   // Element-tier Split: the pre-split seed, and the custom seed we produced
  splitOriginalStyle: null,   // the Style (Fill/Stroke) the Element had before a Segment split forced it to Fill — restored by 'All'
  splitKeep: new Set(),       // Split: which of tl/tr/bl/br are currently kept (empty = whole shape)
  splitCache: null,           // {key, pieces} — splitElementGeometry() result for the current pre-split seed, so toggling chips doesn't re-run Paper
  splitCombinedRaw: null,     // the raw (unfitted) concatenated `d` of the currently-kept quadrants — reused by "Save piece as Seed"
  preFigureSnapshot: null,   // Element+Component state captured right before entering Figure — see setTier()
  // The Grid tier's own page is gone — buildFvsGridSVG()/getFvsGrid() are kept as
  // page-less helpers (Figure recipes and the regression suite's v1 recipe
  // fixtures both still tile), reading this plain config object instead of DOM controls.
  fvsGridConfig: { type: 'square4x4', cellSize: 110, gap: 0, altFlip: false, rot: 0, mirror: 'none' },
  fvsGridComponentName: null,  // when set, the Grid tiles this saved Component directly (componentTileEntry) instead of a Symbol
  fvsGridSymbolName: null,   // name of the saved Symbol (SYMBOL_LIBRARY entry) currently tiled
  symbolGrid: null,   // same shape as loomGrid — a SECOND, independent Loom grid for the Symbols tier
  symbolCells: [],    // one per resolveGridCells(symbolGrid) index:
                       //   {source:'seed', seedType, rotation, flipH, flipV, scale, color,
                       //    fitMode:'contain'|'fill'|'fixed', fixedSize, anchorX, anchorY, padding}
                       //   {source:'component', componentName, rotation, flipH, flipV, scale, fitMode, fixedSize, anchorX, anchorY, padding}
  symbolPool: [],   // [{name, weight}] — the saved Components a Symbol is built from (Arrange / Suggest). "Pool", not "Palette" — Palette is colour only.
  symbolSuggestions: [],   // the last Suggest gallery ({label, score, cells}), tied to the current grid
  symbolSelection: new Set(),   // cell indices, Manual mode's click-to-select — never persisted (editing-session-only)
  symbolMarqueeRect: null,      // {x,y,w,h} in the canvas's own 0..size space, live during a drag-select — preview-only, never persisted or exported
  symbolClipEnabled: false,     // Symbol-level: clip each cell's content to its own bounds (rect/polygon). OFF (the default since the toggles moved to the floatbar) allows bleed; persisted per saved Symbol.
  symbolView: { outline: false, cover: false, guides: true },   // preview-only overlays, toggled from the floatbar: the loaded grid's lines, the cover-crop preview, the column/row guides
};

// ── Palette — centralised colour assignment (moved out of Seed, which
// is now pure shape geometry). Promoted to shared/palette.js
// (Organica.palette.swatch; folded in from organica-palette-chip.js,
// 2026-08-29) — this was one of the 6
// independent copies found duplicating it. min 1 (a single colour IS a
// plain flat fill, the old Fill default) rather than the RMX-standard
// min-2, since a one-Seed single-cell-colour grid is a legitimate
// baseline here, not a degenerate case. Max 8, matching Vortex's own
// ceiling (no shader array-size bound applies).
const PALETTE_MAX = 8;
function colorAt(i) { return state.colors[i % state.colors.length]; }

// ── Colour rule — WHICH palette colour a cell gets. `index` is the original
// behaviour (cell i → colour i, wrapping); the others read the cell's grid
// position so a multi-ink pattern follows the structure (checker parity,
// rows, columns, diagonals, quadrants) instead of the row-major order.
// `own` (the default, Oct 4, 2026): a saved Element placed in a Symbol cell keeps the
// palette it was saved with (cell.ownColors); every other cell — and every Component
// cell — is coloured by cell order.
const COLOR_RULES = {
  own:      { label: "Element's own colours", fn: (i) => i },
  index:    { label: 'By cell order',  fn: (i) => i },
  checker:  { label: 'Checkerboard',   fn: (i, c) => c.col + c.row },
  rows:     { label: 'By row',         fn: (i, c) => c.row },
  columns:  { label: 'By column',      fn: (i, c) => c.col },
  diagonal: { label: 'Diagonal bands', fn: (i, c) => c.col + c.row },
  quadrant: { label: 'By quadrant',    fn: (i, c) => (c.col * 2 >= c.cols ? 1 : 0) + (c.row * 2 >= c.rows ? 2 : 0) },
};
const DEFAULT_COLOR_RULE = { mode: 'own', offset: 0 };
state.colorRule = { ...DEFAULT_COLOR_RULE };
// `checker` alternates between two neighbours only, whatever the palette size.
function paletteInk(colors, rule, i, cr) {
  const r = rule || DEFAULT_COLOR_RULE;
  const def = COLOR_RULES[r.mode] || COLOR_RULES.index;
  let k = def.fn(i, cr ? cr[i] : { col: i, row: 0, cols: 1, rows: 1 }) + (r.offset || 0);
  if (r.mode === 'checker') k = ((k % 2) + 2) % 2;
  const n = colors.length;
  return colors[((k % n) + n) % n];
}
// col/row of every cell of a Component/Symbol grid (binning fallback, so it
// works for square and Loom grids alike). Null when the rule needs no position.
function colorRuleCR(grid, rule) {
  if (!grid || !rule || rule.mode === 'index' || rule.mode === 'own') return null;
  try { return Organica.shapes.cellColRow(grid, null, null); } catch (e) { return null; }
}
// Ink of cell i under the LIVE palette + rule.
function ruleInk(i, cr) { return paletteInk(state.colors, state.colorRule, i, cr); }
// Same for a saved Component entry (its own palette + rule), as a j → colour fn.
function entryInkAt(entry) {
  const cr = colorRuleCR(entry.grid, entry.colorRule);
  return j => paletteInk(entry.colors, entry.colorRule, j, cr);
}
// A Symbol cell's ink. `color: null` = follow the palette (what new cells
// store). A stored colour equal to the palette entry for that index — how
// older saves wrote it — is treated the same, so recolouring the palette
// recolours those cells too; any other stored colour is a real override.
let _symCR = { key: null, rule: null, cr: null };
function symbolCR() {
  const g = state.symbolGrid, r = state.colorRule.mode;
  if (_symCR.key !== g || _symCR.rule !== r) _symCR = { key: g, rule: r, cr: (r === 'index' || r === 'own') ? null : colorRuleCR(getSymbolGrid(), state.colorRule) };
  return _symCR.cr;
}
// "Element's own colours": the cell's saved Element palette, when it has one.
const cellOwnInks = cell => (state.colorRule.mode === 'own' && cell.ownColors && cell.ownColors.length) ? cell.ownColors : null;
function cellInk(cell, i) {
  const own = cellOwnInks(cell);
  const p = own ? own[0] : ruleInk(i, symbolCR());
  // null = follow the palette; anything else is an explicit override set in Cell properties
  // (legacy colours that merely pinned the palette value are released when a saved Symbol loads).
  return cell.color ? cell.color : p;
}

function buildPalette() {
  Organica.palette.swatch(ctrl('fvs-palette'), {
    colors: state.colors,
    min: 1,
    max: PALETTE_MAX,
    onChange: (colors) => {
      state.colors = colors.map(hexKey);
      syncColorRuleUI();
      syncGroundInkOptions();
      refreshColourViews();
    },
  });
  syncGroundInkOptions();
}

function syncColorRuleUI() {
  const sel = ctrl('sel-color-rule'), off = ctrl('sel-color-offset');
  if (!sel.options.length) Object.entries(COLOR_RULES).forEach(([k, v]) => sel.add(new Option(v.label, k)));
  const n = Math.max(1, state.colors.length);
  off.innerHTML = '';
  for (let i = 0; i < n; i++) off.add(new Option('Colour ' + (i + 1), i));
  sel.value = state.colorRule.mode;
  off.value = String(Math.min(state.colorRule.offset || 0, n - 1));
  ctrl('row-color-offset').style.display = n < 2 ? 'none' : '';
  syncQuadrantHint();
}
// "By quadrant" splits the grid at its middle; with an odd number of columns
// or rows the middle line runs through a cell, which is documented behaviour
// (that cell joins the second half) — so it is only flagged, never changed.
function syncQuadrantHint() {
  let odd = false;
  if (state.colorRule.mode === 'quadrant') {
    try {
      const cr = state.activeTier === 'symbol' ? (state.symbolGrid ? cellColRow(getSymbolGrid()) : []) : componentCellColRow(getGrid());
      if (cr.length) odd = (Math.max(...cr.map(c => c.col)) + 1) % 2 === 1 || (Math.max(...cr.map(c => c.row)) + 1) % 2 === 1;
    } catch (e) { odd = false; }
  }
  ctrl('color-quadrant-hint').style.display = odd ? '' : 'none';
}
function refreshColourViews() {
  renderGallery();
  renderSeedPreview();
  if (state.symbolGrid) renderSymbolCanvasOnly();
}
function onColorRuleChange() {
  state.colorRule = { mode: ctrl('sel-color-rule').value, offset: parseInt(ctrl('sel-color-offset').value, 10) || 0 };
  syncColorRuleUI();
  refreshColourViews();
}
