// Flexible Visual System · engine/00-core — the engine part of 00-core.js: model + logic, no DOM UI.
// Uses no panel control, page element or timer — only the model (state, the saved-item stores), pure Organica maths
// and the offscreen measuring helpers. Chosen mechanically by scripts/fvs-engine.mjs. Map: docs/FVS.md §Architecture.
// Paper tile dropdown (Organica.selectPicker) — declared up here: renderSeedPreview, which
// refreshes its "Current Element" thumbnail, runs during boot before the tile code below.
export const TILE_PICK_REG = {};
export const state = {
  components: [],   // [{id, ruleSource, cells:[{rotation,flipH,flipV,scale,content} x4]}]
                     // cell.content: null (default, follow the shared Element) or
                     // {source:'seed', seedType, seedParams} — set live in Component Edit mode
  selectedId: null,
  selectionExplicit: false,   // true once selectedId was set by a real action (click/Generate/quick-save/Library load), not just the starter gallery's own passive default — gates the .selected border in renderGallery()
  // ── Component Edit mode — a big single-component view (enterComponentEditMode)
  // where each cell is clickable and, once selected, the Element sidebar edits
  // THAT cell's own shape live. Editing never mutates the source component —
  // "Save as new" (saveComponentEditAsNew) pushes a fresh gallery candidate.
  componentEditMode: false,
  componentEditId: null,          // the component being edited FROM (read-only source, never mutated)
  componentEditCells: null,       // working copy of cells, edited in place while in this mode
  componentEditGrid: null,        // grid snapshot at entry — fixed for the duration (per design decision)
  componentEditSelectedCell: null,   // index into componentEditCells, or null
  componentEditDefaultSeed: null,    // seedForSnapshot() frozen at entry — the shared Element every non-overridden cell keeps using
  componentEditDefaultAppearance: null,   // getElementAppearance() frozen at entry — same idea, for Style/Width/Length/Scale/Move
  componentAutoGenerated: null,       // null = never populated this session; true = the current gallery is the live, untouched starter set; false = the user did something explicit (Generate/Manual/Clear/a Library load)
  componentAutoGenSignature: null,    // signature of (seed, appearance, cell count) at the moment the starter set was last (re)built
  colors: ['#000000'],   // the centralised Palette (Ink) — see buildPalette()/colorAt() below
  paperColor: '#ffffff',   // the ground every render/export paints against
  customSeed: null,   // {d, normTx, normTy, normScale} from an uploaded SVG, or null
  layers: null,       // null = a plain single-shape Element. Else {items:[{id,name,role:'fill'|'mask'|'container',ink:'cell'|slot,place:{mx,my,scale,rotate},seed}], active} — a stack, bottom→top; the Seed panel edits items[active]
  componentRole: 'normal',           // 'normal' | 'container' | 'mask' — this Component's own silhouette used as a clip/knockout boundary for underlyingComponentName
  underlyingComponentName: null,     // another saved Component Library entry's name, or null
  loomGrid: null,   // {cellShape, cells, inner:{width,height}} from Organica.loadLoomGrid, or null until a file is imported
  activeTier: 'element',   // 'element' | 'component' | 'symbol' | 'figure'
  splitOriginal: null, splitApplied: null,   // Element-tier Split: the pre-split seed, and the custom seed we produced
  splitOriginalStyle: null,   // the Style (Fill/Stroke) the Element had before a Segment split forced it to Fill — restored by 'All'
  splitKeep: new Set(),       // Split: which of tl/tr/bl/br are currently kept (empty = whole shape)
  splitCache: null,           // {key, pieces} — splitElementGeometry() result for the current pre-split seed, so toggling chips doesn't re-run Paper
  splitCombinedRaw: null,     // the raw (unfitted) concatenated `d` of the currently-kept quadrants — reused by "Save piece as Seed"
  preFigureSnapshot: null,   // Element+Component state captured right before entering Figure — see setTier()
  // The Grid tier's own page is gone — buildFvsGridSVG()/getFvsGrid() are kept as
  // page-less helpers (Figure recipes and the regression suite's v1 recipe
  // fixtures both still tile), reading this plain config object instead of DOM controls.
  fvsGridConfig: { type: 'square4x4', cellSize: 110, gap: 0, altFlip: false, rot: 0, mirror: 'none' },
  fvsGridComponentName: null,  // when set, the Grid tiles this saved Component directly (componentTileEntry) instead of a Symbol
  fvsGridSymbolName: null,   // name of the saved Symbol (SYMBOL_LIBRARY entry) currently tiled
  symbolGrid: null,   // same shape as loomGrid — a SECOND, independent Loom grid for the Symbols tier
  symbolCells: [],    // one per resolveGridCells(symbolGrid) index:
                       //   {source:'seed', seedType, rotation, flipH, flipV, scale, color,
                       //    fitMode:'contain'|'fill'|'fixed', fixedSize, anchorX, anchorY, padding}
                       //   {source:'component', componentName, rotation, flipH, flipV, scale, fitMode, fixedSize, anchorX, anchorY, padding}
  symbolPool: [],   // [{name, weight}] — the saved Components a Symbol is built from (Arrange / Suggest). "Pool", not "Palette" — Palette is colour only.
  symbolSuggestions: [],   // the last Suggest gallery ({label, score, cells}), tied to the current grid
  symbolSelection: new Set(),   // cell indices, Manual mode's click-to-select — never persisted (editing-session-only)
  symbolMarqueeRect: null,      // {x,y,w,h} in the canvas's own 0..size space, live during a drag-select — preview-only, never persisted or exported
  symbolClipEnabled: false,     // Symbol-level: clip each cell's content to its own bounds (rect/polygon). OFF (the default since the toggles moved to the floatbar) allows bleed; persisted per saved Symbol.
  symbolView: { outline: false, cover: false, guides: true },   // preview-only overlays, toggled from the floatbar: the loaded grid's lines, the cover-crop preview, the column/row guides
};
// ── Palette — centralised colour assignment (moved out of Seed, which
// is now pure shape geometry). Promoted to shared/palette.js
// (Organica.palette.swatch; folded in from organica-palette-chip.js,
// 2026-08-29) — this was one of the 6
// independent copies found duplicating it. min 1 (a single colour IS a
// plain flat fill, the old Fill default) rather than the RMX-standard
// min-2, since a one-Seed single-cell-colour grid is a legitimate
// baseline here, not a degenerate case. Max 8, matching Vortex's own
// ceiling (no shader array-size bound applies).
export const PALETTE_MAX = 8;
export function colorAt(i) { return state.colors[i % state.colors.length]; }
// ── Colour rule — WHICH palette colour a cell gets. `index` is the original
// behaviour (cell i → colour i, wrapping); the others read the cell's grid
// position so a multi-ink pattern follows the structure (checker parity,
// rows, columns, diagonals, quadrants) instead of the row-major order.
// `own` (the default, Oct 4, 2026): a saved Element placed in a Symbol cell keeps the
// palette it was saved with (cell.ownColors); every other cell — and every Component
// cell — is coloured by cell order.
export const COLOR_RULES = {
  own:      { label: "Element's own colours", fn: (i) => i },
  index:    { label: 'By cell order',  fn: (i) => i },
  checker:  { label: 'Checkerboard',   fn: (i, c) => c.col + c.row },
  rows:     { label: 'By row',         fn: (i, c) => c.row },
  columns:  { label: 'By column',      fn: (i, c) => c.col },
  diagonal: { label: 'Diagonal bands', fn: (i, c) => c.col + c.row },
  quadrant: { label: 'By quadrant',    fn: (i, c) => (c.col * 2 >= c.cols ? 1 : 0) + (c.row * 2 >= c.rows ? 2 : 0) },
};
export const DEFAULT_COLOR_RULE = { mode: 'own', offset: 0 };
// `checker` alternates between two neighbours only, whatever the palette size.
export function paletteInk(colors, rule, i, cr) {
  const r = rule || DEFAULT_COLOR_RULE;
  const def = COLOR_RULES[r.mode] || COLOR_RULES.index;
  let k = def.fn(i, cr ? cr[i] : { col: i, row: 0, cols: 1, rows: 1 }) + (r.offset || 0);
  if (r.mode === 'checker') k = ((k % 2) + 2) % 2;
  const n = colors.length;
  return colors[((k % n) + n) % n];
}
// col/row of every cell of a Component/Symbol grid (binning fallback, so it
// works for square and Loom grids alike). Null when the rule needs no position.
export function colorRuleCR(grid, rule) {
  if (!grid || !rule || rule.mode === 'index' || rule.mode === 'own') return null;
  try { return Organica.shapes.cellColRow(grid, null, null); } catch (e) { return null; }
}
// Ink of cell i under the LIVE palette + rule.
export function ruleInk(i, cr) { return paletteInk(state.colors, state.colorRule, i, cr); }
// Same for a saved Component entry (its own palette + rule), as a j → colour fn.
export function entryInkAt(entry) {
  const cr = colorRuleCR(entry.grid, entry.colorRule);
  return j => paletteInk(entry.colors, entry.colorRule, j, cr);
}
// "Element's own colours": the cell's saved Element palette, when it has one.
export const cellOwnInks = cell => (state.colorRule.mode === 'own' && cell.ownColors && cell.ownColors.length) ? cell.ownColors : null;
